### ISSUE TITLE
The web uses "URL", not "URI"

### ISSUE THREAD

**Issue by domenic** [bokand/page-collection#2]
See https://url.spec.whatwg.org/#url-apis-elsewhere.

I imagine you might be influenced by the existing `text/uri-list` MIME type. If reusing that is necessary, then maybe that's fine. But don't spread that further in the platform via a new URL scheme.

/cc @annevk

**Comment by domenic** [comment]
This also comes up in non-technical places, e.g. repeated mentions of `data:` "URIs".

**Comment by bokand** [comment]
Thanks, I hadn't seen that. Yeah, this comes from `text/uri-list` and I spent a lot of time reading RFCs...

I'll go through the explainer and update it. Given that maybe `text/uri-list` may not be the best fit, per #6, we could probably get away from "URI" completely.

**Comment by annevk** [comment]
FWIW: when I have to use URI I like to suffix it with [sic] to make it clear it's only there because it had to be verbatim.
