### ISSUE TITLE
Some unescaped content in the explainer

### ISSUE THREAD

**Issue by domenic** [bokand/page-collection#3]
Found two so far while skimming, but it'd be worth doing a re-read:

> We also extended text/uri-list (in a backwards compatible way) to allow adding some configuration options. Options can be specified at the end of the resource by placing a key=value pair in a comment with ‘?’ as the first character. For example:
> 
> https://en.wikipedia.org/wiki/Cat https://www.reddit.com/r/catmemes/ #?group-name=Cat Links
> 
> Only a single configuration option will be supported at this time: group-name

and

> A new HTML element (e.g. )

**Comment by bokand** [comment]
Thank you!
